//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public long Item_ID { get; set; }
        public string Item_Description { get; set; }
        public byte Item_Status { get; set; }
        public long To_Do_ID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual TO_DO TO_DO { get; set; }
    }
}
